### ISSUE TITLE
[Suggestion] Sound on dice addition

### ISSUE THREAD

**Issue by VladGrant** [SDoehren/tension-pool#1]
Besides the notification and possibly a a really cool feature would be to play a sound, like a dice falling in cup, to get everyone's attention.

**Comment by SDoehren** [comment]
In the next release there will be an option to "drop a die" when it is added to the pool.  
This will roll the added die on screen, with the result ignored, to show the die being added.  
This will provide and visual and auditory notification via Dice So Nice.

**Comment by SDoehren** [comment]
The latest release is live and includes this feature
