### ISSUE TITLE
Race condition can get `diceinpool` greater than `maxdiceinpool`

### ISSUE THREAD

**Issue by Mejari** [SDoehren/tension-pool#15]
Clicking on the tension pool boxes below the chat box or clicking on the "Add dice to pool" button can sometimes double-up an addition of dice, leading to a number of dice in the pool greater than the max. Every time after that when a dice is added the pool is rolled but the number of dice is incremented and not emptied. Also attempting to manually empty the pool with "Empty the pool (no roll)" does roll and does not empty the pool.

![image](https://user-images.githubusercontent.com/1441727/127788349-914ae6fb-c23d-4741-b3aa-e01d96ffd10f.png)

Subtracting a die seems to cause the system to start working correctly with the next change (i.e. "Add dice" rolls the pool and empties correctly)

The effect is easily reproducible if you click the add dice button very quickly, but can happen on more normal usage rarely as well.

**Comment by SDoehren** [comment]
thanks for raising.  I'm actually aware of this race condition but as it is rare in normal usage i have left it as a "until someone raises it it can stay".  i will have a look into potential solutions as you have now raised it.

**Comment by SDoehren** [comment]
Fix implemented in 0.0.50.

Thanks for raising.
