### ISSUE TITLE
Remove player's ability to add dice

### ISSUE THREAD

**Issue by Nedrapter** [SDoehren/tension-pool#16]
From what I saw the module allows players to also add dice (although it adds to their counter only and not to the DM). It might not affect much but feels unwanted, as the players don't have any rights to be adding dice and many fidgety players will click things many times (for no reason). If it does have a functionality, it'd be preferable to have it optional as a setting and the default to be only the DM adding/rolling.

**Comment by SDoehren** [comment]
It does not have functionality, the player does not have have permission to add to the main counter.  All the same, removed as a behaviour as it is unintended.  Thanks for raising.

**Comment by SDoehren** [comment]
Fix applied in latest release.
