### ISSUE TITLE
Remove changelog pop-up.

### ISSUE THREAD

**Issue by Varriount** [SDoehren/tension-pool#17]
Please remove the changelog pop-up mechanism. DMs only need to know what has changed in a module when there is some major UI or workflow change, and I can't think of *any* situation that requires users to know a module's changelog. Plus, if someone wants to see a module's changelog, there's a place in the module's manifest for it (which will also show up on Foundry's website).

**Comment by SDoehren** [comment]
You should be able to stop it appearing between updates so you only see it once per update.  

I have been pondering absolute removal of the pop up so it is under consideration.

**Comment by Varriount** [comment]
Some food for thought: how do you think users would feel if every module did this?

**Comment by SDoehren** [comment]
I realise where you are coming from but many modules are doing this and it doesn't massively bother me.

As I said, it's under consideration for removal.  I was hoping it would reduce requests for things that are implemented but that hasn't really happened.
