### ISSUE TITLE
Partial pool shouldn't clear

### ISSUE THREAD

**Issue by KevinMacDermid** [SDoehren/tension-pool#2]
Hello,
Thanks for making this! I've been itching to have something like it given the online-only games!

Unless I'm mistaken though the pool shouldn't empty when a partial pool is rolled? I just reread Angry's article on it and the only way it should empty is if it's full.

**Comment by SDoehren** [comment]
No problem.

Someone else mentioned this to me and i fully agree.  It has already been addressed in the next release.  Next release is due tomorrow. 

The other big change coming this release is a continual visible marker of dice in the pool.

**Comment by SDoehren** [comment]
The latest release is live and includes this feature

**Comment by KevinMacDermid** [comment]
Now that's service! Thank you. Was also really interested in the visible marker of the dice pool but didn't want to confuse the ticket by mentioning it, glad to hear you put it in.
