### ISSUE TITLE
Button / command for "add a die and roll"

### ISSUE THREAD

**Issue by piquan** [SDoehren/tension-pool#21]
**Is your feature request related to a problem? Please describe.**
In many circumstances, a PC takes an action that is both Time-Consuming and Reckless. If I'm reading your README.md correctly, there is not currently a command to handle this.
It would be convenient to be able to do this in a single command.

**Describe the solution you'd like**
I would like there to be a command (button and chat command) to simultaneously add a die and roll. The basic concept would be something like this pseudocode:
```
async function adddieandroll(){
  await adddie_do_not_roll();
  await rollpool();
  // == because a count>1 is not yet handled anyway.
  if (diceinpool == maxdiceinpool) {
    // These rolls will both have max dice!
    await rollpool();
    await emptypool();
  }
}
```

**Describe alternatives you've considered**
One might suppose that you could simply use a macro to issue `/TPadddie` followed by `/TProllpool`. However, this is not quite the same in the case when there are five dice in the pool.
As noted in Angry's article at https://theangrygm.com/definitive-tension-pool/ (after some edits he added; see "Rolling the Pool Twice"), when there are five dice in the Tension Pool and a sixth die is added, you typically roll the pool once.
He does talk about rolling it twice in some circumstances (although doesn't make it clear if this is two rolls of a full pool, or what). This is something that could be managed by a Setting or a popup query.

**Additional context**
I wrote something similar to this privately for Roll20. When I did that, I found that handling this situation really added complexity to the logic; I ended up having to refactor a lot of the code to handle these concepts. So I have empathy for why you may not have written this yet, but being able to quickly resolve an action correctly is important for a GM.

**Comment by SDoehren** [comment]
thanks for the suggestion.  

the logic isn't too bad, the bigger issue is that it is another button.  

i will add in some options around the buttons then implement this, its a sensible addition.

**Comment by piquan** [comment]
For sure; from a UI perspective, adding new buttons isn't great.
Personally, if I were designing the UI, I would focus on the three actions that Angry suggests: add a die, roll the pool, or add a die and roll the pool. Some other actions (remove a die or empty pool) aren't part of Angry's suggestion, so I might include them as chat commands (so they could easily be written into the macro bar) but not buttons. Since "/TP "Fill and Roll Pool" can also easily be handled in a macro effectively as "/r 6d6" followed by "/TPemptypool".
Of course, my ideas of UI design are very strongly influenced by the features I personally use. I don't know what the rest of your userbase does, so take my thoughts with a grain of salt.

**Comment by SDoehren** [comment]
Remove a die or empty pool are both there for functional reasons.  The former for accidental clicks, the latter for when you leave the tension situation.

FYI there is an API that is easier for macros than the chat commands https://github.com/SDoehren/tension-pool/blob/master/api.md

While I'm added to the main module, this macro should do exactly what you want.

    async function addandrollpool() {
        let DICE = game.settings.get("tension-pool", 'diceinpool');
        let MAXDICE = game.settings.get("tension-pool", 'maxdiceinpool');

        if (DICE < MAXDICE - 1) {
            game.tension.rollcustompool(DICE + 1, "Die added and Pool Rolled");
            game.settings.set("tension-pool", "diceinpool", DICE + 1);
        } else {
            game.tension.adddie()
        }
    }
    addandrollpool()

**Comment by SDoehren** [comment]
Released in V0053
