### ISSUE TITLE
Whisper results of roll to GM setting.

### ISSUE THREAD

**Issue by Schwenckenator** [SDoehren/tension-pool#22]
**Is your feature request related to a problem? Please describe.**
At the moment, when the tension pool is rolled the results are in the chat for all to see including the players. There seems to be no way to change this.

**Describe the solution you'd like**
I'd like there to be a setting which hides the results of a tension pool roll from the players.

Thanks!

**Comment by SDoehren** [comment]
you are correct, no current way to change this.  it is a sensible suggestion that i will look to get in the next version.

**Comment by Schwenckenator** [comment]
Wow, that was quick! Thank you very much!

**Comment by SDoehren** [comment]
Released in V0053
