### ISSUE TITLE
All Settings Available to Players

### ISSUE THREAD

**Issue by Shuggaloaf** [SDoehren/tension-pool#24]
I'm not sure if this is a bug or as intended but my players can see and alter every single setting option. Obviously players have no need to do so. Please consider blocking settings access for players. 

Thanks!

**Comment by SDoehren** [comment]
are your players setup as players or trusted players?

can i get you foundry version, system a d system version?

Modules have very little control over what players/GMs see, it's basically an on/off switch.

**Comment by Shuggaloaf** [comment]
Just standard players.

FVTT 0.8.9 // DND5e 1.5.3

>Modules have very little control over what players/GMs see, it's basically an on/off switch.

I may be misunderstanding your meaning but this doesn't seem right based on other mods I have installed, which many of them only show some settings to players, or none at all. 

Or maybe I wasn't being clear - I don't mean all FVTT settings or all installed mods settings, I mean players can see all _Tension Pool_ settings. So an "off switch" as you mention would be perfect as I don't think players should see (or edit) the TP settings.

**Comment by SDoehren** [comment]
Don't worry, I realised I set this module up differently.  I need to put in a filter, will be in the next release.

**Comment by Shuggaloaf** [comment]
OK great, thanks for taking another look at it! 

So just to confirm, the next release players will see no options at all?

**Comment by SDoehren** [comment]
That's the plan.  I cant think of anything players need to see.

**Comment by Shuggaloaf** [comment]
Nice! Thanks SD

**Comment by SDoehren** [comment]
V0055 has been released, this issue should be resolved.  Let me know if you have further issues.
