### ISSUE TITLE
Roll full dice pool

### ISSUE THREAD

**Issue by corerupt83** [SDoehren/tension-pool#25]
**Describe the bug**
Not sure if it is a bug, rather than an outdated function based on Angry GM's post. Possibly a bug though

**To Reproduce**
Clicking "Roll Full Dice Pool" button, fills the current pool, then rolls the dice, and empties the pool.

**Expected behavior**
Clicking "Roll Full Dice Pool" button. Should roll the max pool size in dice, leaving whatever is in the pool untouched. This is for moments when the party do something that would consume more time. 
For example: Poll size is 6 dice. Each die represents 10 minutes of time. Current pool has 3 dice in it, then the party do something that would take an hour. You would roll a full pool and leave the current pool total in tact.

**Screenshots**

**Foundry (please complete the following information):**
 - Foundry Version 0.8.9
 - System PF2E
 - Module Version 0055

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser n/a - Using foundry software
 - Version n/a

**Additional context**

**Comment by SDoehren** [comment]
Hi, thanks for the message.

Roll Full Dice Pool is a fill, roll and empty, as per the Angry GM.

> Roll and Clear the Pool. And finally, whenever you add the sixth die to the pool, no matter what, you roll all the dice in the Tension Pool and then put the dice aside, clearing the pool

Whenever the dice pool is full, it should be rolled and emptied.

You are mistaking it with 

> Add a Die, Then Roll the Pool. You add a die and then roll the pool whenever the party does something reckless, crazy, or dangerous that also chews up whatever amount of time each die represents.

For which tension pool has the option to empty the pool after or not.

I will investigate the possibility of that you are looking for though.

**Comment by corerupt83** [comment]
Yeah, the post you are basing the system off has been iterated on since.
https://theangrygm.com/tension-on-the-road/
that's Angry GM's fleshed out version of the Tension/Time Pool.

Specifically the following:

- **Add a Die:** Pick up a d6 and visibly drop it in the pool. If you just added the sixth die to the pool, immediately Clear the Pool.
- **Roll the Pool:** Pick up all the dice currently in the pool and roll them. Take note if any of the dice show a 1. Then, put the dice back in the pool. If the pool is currently empty, roll one d6 by itself, note if it shows a 1, and then put that d6 aside. Don’t add it to the pool.
- **Add a Die and Roll the Pool:** Pick up a d6 and visibly drop it in the pool. If that’s the sixth die, immediately Clear the Pool. Otherwise, after adding the d6, pick up all the dice currently in the pool and roll them. Take note if any dice show a 1. Then, put the dice back in the pool.
- **Roll a Full Pool:** Ignore what’s in the pool. Pick up 6d6 and roll them. Take note if any of the dice show a 1. Don’t change the pool in any way. **<-----(this is the function I'm looking for, that does not exist in your module)**
- **Clear the Pool:** If there are six dice in the pool, pick them all up and roll them. Take note if any of the dice show a 1. Regardless of the result, don’t return the dice to the pool. The pool is now empty.

This is not a slant to your great work btw, it's just using the "outdated" version of the rules he made up. Of course even if you don't change anything your module is still great and I can just work around it. But if you do get round to adding that functionality I would be grateful.

**Comment by corerupt83** [comment]
In fact you don't really need to change anything or add anything. I can just make a macro to roll 6d6. That wont add, or take away, or reset what your module is doing. Don't know why I didn't think of it till now.
I guess I was wishing it was all contained in your neat work ^^
But thank you either way.

**Comment by SDoehren** [comment]
thanks for the notes.  i think i need to give the updated article a good read to try and get the new rules in.

if you are using the custom tension pool dice with the !, 6dt will roll those instead.

**Comment by corerupt83** [comment]
Oh ok, perfect thanks :)

**Comment by kinland** [comment]
this sounds like a pretty minor change. if I have time, I'll look into adding it and opening a PR

**Comment by SDoehren** [comment]
Implemented in next version.

**Comment by SDoehren** [comment]
Added
