### ISSUE TITLE
Incaompatible with V9

### ISSUE THREAD

**Issue by TMunsie** [SDoehren/tension-pool#27]
Tension pool is causing black screening of the canvas in V9 by being activated.

![image](https://user-images.githubusercontent.com/25963508/146687007-79a40b52-e2b5-4a01-ba5b-65abbc738e77.png)

![image](https://user-images.githubusercontent.com/25963508/146687016-9dc96997-5c1c-46c1-a2bb-2ef2fb04b534.png)

**Comment by SDoehren** [comment]
V9 is not currently supported.

**Comment by SDoehren** [comment]
Resolved in latest release

**Comment by TMunsie** [comment]
Updated Foundry spreadsheet. Thanks!
