### ISSUE TITLE
Can't delete chat log with Tension Pool enabled

### ISSUE THREAD

**Issue by ctbritt** [SDoehren/tension-pool#28]
**Describe the bug**
Clear Chat log button doesn't respond when Tension Pool is enabled 

**To Reproduce**
1. Enable Tension Pool
2. Try to clear chat log
3. button is unresponsive

**Expected behavior**
Chat log dialog should appear

**Screenshots**

**Foundry (please complete the following information):**
 - Foundry Version 9.238
 - System Dnd5e 1.5.6
 - Module Version 0056

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 96.0.4664.110

**Additional context**

**Comment by SDoehren** [comment]
Thanks for raising.  
It's an odd one.

**Comment by SDoehren** [comment]
Issue resolved in V0057
