### ISSUE TITLE
Remove Dependency on Dice So Nice

### ISSUE THREAD

**Issue by SabreRunner** [SDoehren/tension-pool#29]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't use this module without Dice So Nice.

**Describe the solution you'd like**
Allow the module to use Dice So Nice but don't require it. Allow it to just roll the pool to the chat.

**Describe alternatives you've considered**
I don't want to use Dice So Nice because I hate 3D dice rolling in VTTs.

**Comment by SDoehren** [comment]
My instinct was this is too fundamental to the code, but having a look at the code I may be to do it with fairly limited changes.

I will give this a look and see what I can do.

**Comment by timartiny** [comment]
I would also love if that dependency could be removed. It can't be disabled by a DM, so each player needs to disable it.

**Comment by SDoehren** [comment]
This has been implemented in v0058
