### ISSUE TITLE
Auto roll on a table when a complication occurs?

### ISSUE THREAD

**Issue by Orionox** [SDoehren/tension-pool#30]
would be cool if we could declare a table that was automatically rolled when a complication occurred

**Comment by SDoehren** [comment]
You can use a macro to do this already.

https://github.com/foundry-vtt-community/macros/blob/main/roll/roll_table.js

**Comment by Orionox** [comment]
How do I connect that with the roll of the tension die though?

**Comment by SDoehren** [comment]
Create the marco

Tension Pool Settings> Run Macro When Complication Occurs > Select the Macro
