### ISSUE TITLE
Visual dice not shown to players when adding dice to pool

### ISSUE THREAD

**Issue by bjornestol** [SDoehren/tension-pool#32]
**Describe the bug**
When adding dice to the dice pool and having the "dropdie" option on, a die is only dropped for the GM.

**To Reproduce**
Add a die to the pool.

**Expected behavior**
The die to be shown to all players, not just the GM.

**Foundry (please complete the following information):**
 - Foundry Version 9 - Build 269
 - Pathfinder 2e & DnD 5e
 - Module Version 0058

**Additional context**
Easily fixed, I'll make a pull request that fixes the problem for me.

**Comment by SDoehren** [comment]
Leaving open until next release.

Thank you for your help.

**Comment by SDoehren** [comment]
Added in the most recent release.
