### ISSUE TITLE
Any chance for v11 update?

### ISSUE THREAD

**Issue by Nedrapter** [SDoehren/tension-pool#38]
As title says, is there a chance for v11 update? This module makes players so tense in my games ^^

**Comment by SDoehren** [comment]
It will get updated at some point.
The when depends on how much work is needed.

**Comment by Nedrapter** [comment]
If it's any help, these are the errors that currently the module shows in v11 when trying to add die in the pool
![image](https://github.com/SDoehren/tension-pool/assets/74311190/4ff861e4-f70c-4911-90ad-f5f25c3d6b88)

**Comment by SDoehren** [comment]
About to release an update.
Can you load foundry and chat if you get a message saying "Currently you do not have Dice So Nice enabled but have the Visual Dice Effects Enabled. Please enable Dice So Nice to use the visual effects."?

I believe the source of that error is Dice So Nice not being enabled.

**Comment by SDoehren** [comment]
Released, I think Dice so nice was the issue, I have put in error handling, let me know if you have any issues.

**Comment by Nedrapter** [comment]
I was testing it first on my local Foundry which is my test lab. Going to the Forge where I run my games, I saw the modules doesnt even let me to install, saying it's incompatible 
![image](https://github.com/SDoehren/tension-pool/assets/74311190/0c2d5bec-f527-486b-9ffc-5c8e85375fbc)

**Comment by SDoehren** [comment]
Try now, should be version 0063.

**Comment by Nedrapter** [comment]
Works like a charm, thank you!
