### ISSUE TITLE
Different danger levels?

### ISSUE THREAD

**Issue by MyklKelsey** [SDoehren/tension-pool#4]
More Feature Request Than Issue, but...
I was wondering if you could add the feature where I can set the die to be added based on the level of danger.

Add a d12 to the pool, because they are spending time in the enemy hideout...
Add a d8 they've caused a ruckus...
Add a d6 they've alerted the guards!
Add a d4 they've really hit the bee's nest!!

So then when you roll the pool the chances of a 1 are higher for the time spent in more dangerous areas?

Maybe this just complicates things too much.

I really like what you have done and will be using it in my game! Thank you so much.

**Comment by SDoehren** [comment]
Thanks.  (gestures broadly at tip jar)

I have considered this in the initial build. I have not looked to add it for 2 reasons.  

1. Adds a lot more to the build than you would expect.  I would need to add a method for picking each dice added, tracking of what is in the pool and find a way to simply represent what is in the pool to the players.  

2. It goes against the ethos of the tension pool design.    
The idea is to set the pool dice to the danger/compilation of the area of the area.  VERY high likelihood of a complication area d4, very low d20.  
You then vary the action based on their behaviour.    
Time passes or they do something minor, add a die  
They do something a bit silly, roll the pool with the current number of dice  
They do something quite silly, add a die  and roll the pool with the current number of dice.  
They do stupid, fill the pool and roll it.

I'm not ruling it out at this stage, but don't expect it soon.
