### ISSUE TITLE
Tension Pool does not update on Player Side

### ISSUE THREAD

**Issue by shinkei13** [SDoehren/tension-pool#5]
FoundryVTT: v0.7.9
Tension Pool: v0.0.12

I'm experimenting with the Tension Pool module, and I've noticed that the Tension Pool itself does not reflect the number of dice rolled on the player's screens.

The notifications appear, and the rolls are all reflected, however the visible pool beneath the chatbox only updates on a player's screen when they refresh. It's possible that the function `updatedisplay(diceinpool)` is not being run locally on the player side.

**Comment by SDoehren** [comment]
Amazing no one has raised this yet.

Spot on on the issue.  Fix released.
