### ISSUE TITLE
Enhancement: Clear the Tension Pool without rolling

### ISSUE THREAD

**Issue by shinkei13** [SDoehren/tension-pool#6]
In one of their [comments](https://theangrygm.com/making-things-complicated/#comment-41383), the Angry GM clarified that "When a scene ends the tension pool goes away and a new one starts."
 
At the moment, this system has no means of clearing the pool to initiate a new scene, without rolling the tension pool as a whole. In the given example of the tension pool representing a bomb's timer running out: what happens to the tension pool when the bomb is defused? The tension should be let out, however there's no option for that right now.

**Comment by SDoehren** [comment]
Makes sense.  Should be pretty simple to add.   I should probably add a minus 1 also for accidental dice adds.  
I will have a look tonight.

**Comment by SDoehren** [comment]
Added, will be in the next release.
