### ISSUE TITLE
Enhancement: Alternate ways to add, roll, or clear Tension Dice

### ISSUE THREAD

**Issue by shinkei13** [SDoehren/tension-pool#7]
Using Minimal UI, I often play with the Scene Tools hidden, and during our session I found myself wondering about alternative methods to add Tension Dice:
1. Using chat commands (such as `/addtd`, `/rolltd`, or `/filltd` for example) to initiate the `adddie()` or `rollpool()` functions.
2. Allowing GMs to click the Tension Pool itself to add or remove dice. It feels like an intuitive next step based on the design, and I found myself more than once trying to click on the tension dice to roll them.

**Comment by SDoehren** [comment]
Both make a lot of sense.  

It probably makes sense just to move the scene controls down to the pool itself so everything is in one place.  Or at least give the option to have the controls there as well/instead.

**Comment by shinkei13** [comment]
I honestly was only mentioning the chat commands for the purposes of automation or macros. 

I.e. if a macro requires a roll or a saving throw, and the players fail, it can use a chat command to add a tension die without needing to go into depth about how to execute the functions themselves.

**Comment by SDoehren** [comment]
Macros are a good shout.

Chat commands have been added.  
Clicking the pool/controls by the pool will come at a later date.  Working out how best to implement.  
Entering a short test phase.  Expect the next release before the weekend.

**Comment by shinkei13** [comment]
> Clicking the pool/controls by the pool will come at a later date. Working out how best to implement.

I cheated a bit and created a macro that did it this way
```
let tensionPoolEmpty = document.querySelectorAll("p#TensionDice-Pool > img[src*='EmptyDie.webp']");
let tensionPoolFull = document.querySelectorAll("p#TensionDice-Pool > img[src*='Danger_black.webp']");
let tensionTitle = $("p#TensionDice-Pool").contents().first().wrap('<span/>').parent();

$(tensionTitle).click(function() {
    console.log("Roll Dice Pool");
    document.querySelector("ol.control-tools li.control-tool[title*='Roll Dice Pool']").click();
});
$(tensionPoolEmpty).on('click', event => {
    console.log("Add Dice to Pool");
    document.querySelector("ol.control-tools li.control-tool[title*='Add Dice to Pool']").click();
});
$(tensionPoolEmpty).on('contextmenu', event => {
    console.log("Roll Full Dice Pool");
    document.querySelector("ol.control-tools li.control-tool[title*='Roll Full Dice Pool']").click();
});
$(tensionPoolFull).on('click', event => {
    console.log("Remove Die from Pool");
    document.querySelector("ol.control-tools li.control-tool[title*='Remove Die from Pool']").click();
});
$(tensionPoolFull).on('contextmenu', event => {
    console.log("Empty the Pool");
    document.querySelector("ol.control-tools li.control-tool[title*='Empty the Pool']").click();
});
```

But I imagine you could do the same by replacing the `document.queryselector.click()` fields with the actual functions themselves.
