### ISSUE TITLE
Enhancement: Call Hook when rolling the Tension Pool

### ISSUE THREAD

**Issue by shinkei13** [SDoehren/tension-pool#8]
Last one I promise!

While I know "Auto Roll on a Roll Table if a Complication occurs" is in the future pipeline, I wondered if it would be possible to add a hook to the `rollpool()` function to allow others to extend automation functionality further? Something like `Hooks.call("tensionpoolrolled", dice, complication);` on line 195 of tension-pool.js would potentially allow the users to hook into the tension roll and react accordingly.

Including the amount of dice in addition to whether or not a complication occurs would also give users the ability to scale the complication to the amount of dice in the pool for example.

**Comment by SDoehren** [comment]
Ha ha, no worries.

This actually crossed my mind yesterday.  
I don't have hook calls in either of my modules currently, so i will need to have a bit of a play to learn it.  
But, once again, I agree that it would be a great addition.

**Comment by SDoehren** [comment]
Added, will be in the next release.

## Hooks Calls

#### On Pool Roll

Hooks.call("tension-poolRolled", dicerolled, diceleftinpool,complicationoccured);

- dicerolled (int) - The dice rolled
- diceleftinpool (int) - The dice left in the pool after the roll is complete
- complicationoccured (bool) - whether a complication should occur

#### On Change in Dice in Pool

Hooks.call("tension-poolChange", diceinpool);

- diceinpool (int) - The dice in the pool after dice added or removed
