### ISSUE TITLE
"Add Dice to Pool" Button in Token Controls Probably Unnecessary.

### ISSUE THREAD

**Issue by JLtheking2** [SDoehren/tension-pool#9]
Hey there! Awesome mod. Been using it lately and its great.

You released an update recently, that added a "Tension Pool Controls" tool providing 5 options which are greatly appreciated. However there is still a button in the Token menu to add dice to the pool. This button already exists in "Tension Pool Controls" so I feel the duplication is unnecessary.

Cheers and thanks again for the mod :)

**Comment by SDoehren** [comment]
Thank you.

Yes, left in in error.

Removed in new release.
